# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "local/fedora27"
  config.vm.provider "hyperv" do |hyperv|
    hyperv.vmname = "fedora-dev"
    hyperv.cpus = "2"
    hyperv.memory = "1024"
    hyperv.maxmemory = "2048"
  end
  config.ssh.password = "vagrant"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
